#Now AWS platform looking for a docker-compose.yml instead Dockerfile
version: '3'
services:
  web:
    build: 
    # context . is where we want to test.
    # we can edit by reactproject of we want to test this reactproject folder
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'