version: '3'
services:
  web:
    build:
    # context . is where we want to test.
    # we can edit by reactproject of we want to test this reactproject folder
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  # for Test services
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"] #replace default command